### ISSUE TITLE
Build of native shared libraries for Android fails on OS X

### ISSUE THREAD

**Issue by peterGraf** [artoolkit/artoolkit5#121]
Hello ARToolKit people,

I use a Mac with the latest OS X and my cc -v results in

```
Peters-Mac-mini:~: cc -v
Apple LLVM version 7.3.0 (clang-703.0.31)
Target: x86_64-apple-darwin15.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

The AS I use is a new download from yesterday, AS 2.1.1,
the NDK is the one it downloaded itself, some version of r11 I think.

I have cloned artoolkit5, and opened the aRNativeOSG example project in AS.
It compiled fine, but when I ran it, it reported that it could not load the libc++shared.so.

After a while I figured that the clone does not contain the .so libraries and they need to be compiled as described in AS_Migration.pdf.

There it says on page 4:

_To build for Android, using a command-line shell (for Windows, the git bash shell), change to the "android" directory under the ARToolKit for Android SDK development root directory. The “build.sh” script file builds the ARTK shared libraries for the Android using the Android NDK toolchain. Execute the script “build.sh” for both building on Mac OS X or Windows 8.1/10. Look to see that all builds without error. Both the Android Studio and Eclipse Android specific example app projects are setup to use the built ARToolKit binaries._

When I run build.sh, I get:

```
Peters-Mac-mini:android: ./build.sh 
Working from directory "/Users/peter/StudioProjects/artoolkit5/android".
Building on Apple Mac OS X (x86_64)
ARToolKit5 Android MK file (armeebi)
ARToolKit5 Android MK file (armeabi-v7a)
ARToolKit5 Android MK file (x86)
ARToolKit5 Android MK file (mips)
ARToolKit5 Android MK file (arm64-v8a)
ARToolKit5 Android MK file (x86_64)
ARToolKit5 Android MK file (mips64)
[armeabi] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/armeabi/
[armeabi-v7a] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/
[x86] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/x86/
[mips] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/mips/
[arm64-v8a] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/
[x86_64] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/x86_64/
[mips64] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/mips64/
[armeabi] Compile arm    : ar <= ar3DCreateHandle.c

...  many files get compiled successfully ...

[armeabi] Compile arm    : arvideo <= videoLuma.c
[armeabi] Compile arm    : arvideo <= videoSaveImage.c
In file included from jni/../../lib/SRC/Video/videoLuma.c:55:
In file included from /Users/peter/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.256229/include/emmintrin.h:27:
In file included from /Users/peter/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.256229/include/xmmintrin.h:27:
/Users/peter/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.256229/include/mmintrin.h:45:12: error: invalid conversion
      between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/peter/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.256229/include/mmintrin.h:69:12: error: invalid conversion
      between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
    return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
```

I have worked around the problem by using the .so files that are included in the Android 
binary download ARToolKit5-bin-5.3.2-Android, but I would like to be able to compile the artoolkit sources myself.

Anybody got an idea what is wrong?

**Comment by winterer** [comment]
I've got the same issue on Windows 10 (x86) when trying to build rev. [35a576da48de583f29](https://github.com/artoolkit/artoolkit5/commit/35a576da48de583f29d551bc20a49f86fee442d7):

> (...)
> ARToolKit5 Android MK file (mips)
> [armeabi] Compile arm    : arvideo <= videoLuma.c
> [armeabi-v7a] Compile arm    : ar <= arDetectMarker2.c
> [armeabi-v7a] Compile arm    : ar <= arFilterTransMat.c
> [armeabi-v7a] Compile arm    : ar <= arGetLine.c
> In file included from jni/../../lib/SRC/Video/videoLuma.c:55:
> In file included from C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin\..\lib64\clang\3.8.256229\include\emmintrin.h:27:
> In file included from C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin\..\lib64\clang\3.8.256229\include\xmmintrin.h:27:
> C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin\..\lib64\clang\3.8.256229\include\mmintrin.h:45:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
>     return (__m64)__builtin_ia32_vec_init_v2si(__i, 0);
>            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> C:/Android/sdk/ndk-bundle/build//../toolchains/llvm/prebuilt/windows-x86_64/bin\..\lib64\clang\3.8.256229\include\mmintrin.h:69:12: error: invalid conversion between vector type '__m64' (vector of 1 'long long' value) and integer type 'int' of different size
>     return (__m64)__builtin_ia32_packsswb((__v4hi)__m1, (__v4hi)__m2);
>            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> (more error lines following)

Any progress on that problem?

**Comment by ThorstenBux** [comment]
Hi @peterGraf,

actually the description how to build the native project can be found here:
http://www.artoolkit.org/documentation/doku.php?id=4_Android:android_native
or here:
https://www.youtube.com/watch?v=GAWyUQ1xaNs

However you already figured that out which is good. In regards to the error, we are working on it. It happening since a merge into master 3 days ago. 

I'll let you know once we fixed it.

**Comment by philip-lamb** [comment]
Two different errors. 1) The AR_HAVE_INTEL_SIMD definition was sneaking through from the linux section of config.h. 2) The cpufeatures library wasn't up to date. Working on the fix now.

**Comment by philip-lamb** [comment]
Fixed in https://github.com/artoolkit/artoolkit5/commit/b1498ce6f67cc2f31c1a3d729fc4f8c168f6d268

**Comment by peterGraf** [comment]
Hello Phillip,

I just tried it, the build.sh now compiles everything warning free.

Thanks and Greetings,

Peter

**Comment by winterer** [comment]
Same here on Windows 10: `build.sh` works now. Good work, Philip!
But I still get errors when building the native examples using `build_native_examples.sh`.
I'll post a new bug on this.

**Comment by philip-lamb** [comment]
We've already got one open. :-) https://github.com/artoolkit/artoolkit5/issues/123
